apiVersion: v1
kind: Service
metadata:
  name: kn-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
{{- if .Values.global.exposeNodePorts }}
    nodePort: 30104
  type: NodePort
{{- end }}
  selector:
    service: kn-api
